// Disionáriu Lian Tetun Murni ba Sistema Informasaun Jestaun Eskola Sekundaria NOSSEF Railaco

export const TETUN = {
  appName: 'Sistema Informasaun Jestaun Eskola Sekundaria Bazeia ba PWA',
  shortAppName: 'NOSSEF PWA',
  school: {
    officialName: 'Escola Secundaria Catolica Nossa Senhora de Fatima Railaco',
    shortName: 'NOSSEF Railaco',
    motto: 'Fé, Siénsia no Karidade ba Futuru Timor-Leste',
    location: 'Railaco Vila, Posto Administrativo Railaco, Munisípiu Ermera, Timor-Leste',
    director: 'Pe. Guilhermino da Silva, SJ',
    phone: '+670 7723 4567',
    email: 'sekretaria.nossef@gmail.com',
  },
  roles: {
    SUPER_ADMIN: 'Administradór Prinsipál Sistema',
    SCHOOL_ADMIN: 'Sekretária & Administrasaun Eskola',
    PRINCIPAL: 'Diretór Eskola',
    CURRICULUM_ADMIN: 'Xefe Departamentu Kurríkulu',
    FINANCE_ADMIN: 'Tezoureiru & Administradór Finansas',
    ADMISSION_OFFICER: 'Ofisiál Admisasaun & Rejistu',
    TEACHER: 'Mestre / Profesór',
    HOMEROOM_TEACHER: 'Mestre Titulár Klase',
    COUNSELOR: 'Orientadór & Konsellór (BK)',
    LIBRARIAN: 'Bibliotekáriu',
    ASSET_OFFICER: 'Responsável Patrimóniu & Sasán',
    STAFF: 'Funsionáriu Administrativu',
    STUDENT: 'Estudante',
    GUARDIAN: 'Enkaregadu de Edukasaun / Inan-Aman',
  },
  nav: {
    dashboard: 'Painél Prinsipál',
    admissions: 'Admisasaun Foun',
    students: 'Dadus Estudante',
    staff: 'Mestre & Funsionáriu',
    academics: 'Estrutura Akadémika',
    schedule: 'Oráriu Aula',
    attendance: 'Prezensas & Falta',
    assessments: 'Avaliasaun & CAU',
    gradebook: 'Kadiadernu Nota',
    reportCards: 'Boletin de Notas',
    nationalExam: 'Ezame Nasionál (12.º)',
    finance: 'Finansas & Mensalidade',
    counseling: 'Konsellu & Disiplina',
    extracurricular: 'Estrakurrikulár',
    library: 'Biblioteka',
    assets: 'Patrimóniu & Sasán',
    communications: 'Avizu & Notifikasaun',
    documents: 'Dokumentu & Arkivu',
    reports: 'Relatóriu Jerál',
    audit: 'Rejistu Audit',
    settings: 'Konfigurasaun',
  },
  auth: {
    loginTitle: 'Tama iha Sistema',
    loginSubtitle: 'Prenxe ita-boot nia email ka naran utilizadór no lia-fukun',
    usernameOrEmail: 'Email ka Naran Utilizadór',
    password: 'Lia-fukun (Password)',
    rememberMe: 'Rai ha\'u-nia sesaun',
    forgotPassword: 'Halua lia-fukun?',
    submitLogin: 'Tama Agora',
    logout: 'Sai husi Sistema',
    loginSuccess: 'Ita-boot konsege tama ona iha sistema!',
    loginFailed: 'Email ka lia-fukun la loos. Favór koko fali.',
    quickLogin: 'Aksesu Lalais tuir Kargu (Demo & Teste):',
    selectRole: 'Hili Kargu',
  },
  status: {
    active: 'Ativu',
    inactive: 'Inativu',
    pending: 'Pendente',
    approved: 'Aprovadu',
    rejected: 'Rejeitadu',
    completed: 'Konkluidu',
    draft: 'Rascunho (Provizóriu)',
    submitted: 'Haruka Ona',
    underReview: 'Haree hela',
    enrolled: 'Matrikuladu',
    graduated: 'Graduadu',
    transferred: 'Transfere Sai',
    suspended: 'Suspende',
    cancelled: 'Kanseladu',
    paid: 'Selu Ona',
    unpaid: 'Seidauk Selu',
    partiallyPaid: 'Selu Balun',
    overdue: 'Atrasu / Dívida',
    reversed: 'Fila Fali (Reversal)',
    locked: 'Trankadu',
    open: 'Loke',
    closed: 'Taka Ona',
    present: 'Prezente',
    absent: 'Falta Sem Justifikasaun',
    permission: 'Lisensa',
    sick: 'Moras',
    late: 'Tarde',
    good: 'Kondisaun Di\'ak',
    damaged: 'Aat / Presiza Hadi\'a',
    lost: 'Lakon',
    promoted: 'Promovidu ba Klase Tuir Mai',
    retained: 'Repete Klase',
    passed: 'Liu Ezame',
    failed: 'La Liu Ezame',
  },
  actions: {
    save: 'Rai Dadus',
    cancel: 'Kansela',
    delete: 'Hamos',
    edit: 'Hadi\'a',
    add: 'Aumenta Foun',
    search: 'Buka dadus...',
    filter: 'Filtru',
    refresh: 'Foun Fali',
    exportCsv: 'Esporta CSV',
    exportPdf: 'Esporta PDF / Imprime',
    import: 'Importa Dadus',
    confirm: 'Konfirma',
    back: 'Fila ba Kotuk',
    close: 'Taka',
    viewDetails: 'Haree Detallu',
    syncNow: 'Sinkroniza Agora',
    lockScores: 'Tranka Nota',
    unlockScores: 'Loke Fali Nota',
    calculateTerm: 'Kalkula Nota Trimestre',
    generateInvoices: 'Kria Konta Mensalidade',
    recordPayment: 'Rejistu Pagamentu',
    reversePayment: 'Fila Pagamentu (Reversal)',
    printReceipt: 'Imprime Resibu',
    printReportCard: 'Imprime Boletin',
    approveLeave: 'Aprova Lisensa',
    rejectLeave: 'Rejeita Lisensa',
  },
  pwa: {
    onlineStatus: 'Konektadu ba Rede (Online)',
    offlineStatus: 'La iha Rede (Offline)',
    syncSuccess: 'Dadus offline konsege sinkroniza ona ho susesu!',
    pendingMutations: 'operasaun pendente atu haruka ba servidór',
    offlineNotice: 'Ita-boot bele kontinua uza sistema ne\'e maski la iha internet. Dadus sei rai iha memória navegadór no sei sinkroniza bainhira internet liga fali.',
  },
  cauMapping: {
    1: 'CAU 1 (Trimestre 1)',
    2: 'CAU 2 (Trimestre 2)',
    3: 'CAU 3 (Trimestre 3)',
  },
  majors: {
    CT: 'Ciências Naturais (Siénsia Naturál / IPA)',
    CSH: 'Ciências Sociais e Humanidades (Siénsia Sosiál / IPS)',
  },
  gradeLevels: {
    10: '10.º Ano (Klase X)',
    11: '11.º Ano (Klase XI)',
    12: '12.º Ano (Klase XII)',
  },
};
